# Oh yeah!
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false

# Add additional versions here as appropriate.
node_js:
  - "stable"
  - "9"
  - "8"

# Lint errors should trigger a failure.
before_script:
  - npm run lint
  - npm run build

# Runs the coverage script (which runs the tests)
script: npm run coveralls

after_success:
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
